#!/bin/bash
# ~/.bash_profile: executed by bash(1) for login shells.

# default to urxvt instead of xterm
export TERMINAL=urxvt

# include .profile if it exists
if [ -f "${HOME}/.profile" ] && [ -r "${HOME}/.profile" ]; then
    source "${HOME}/.profile"
fi