# comment to keep editor from exploding in rage, jinja still applies...
# {% from "maps/ports.jinja" import ports with context %}

# We use nginx as the access point; this ensures that nothing else
# is allowed general network access. 

version: "3"
services:
  sillytavern:
    build:
      context: ./sillytavern/.
    image: sillytavern:local # local tag
    container_name: sillytavern
    volumes:
      - "{{ silly_tavern_config_loc }}:/home/node/app/config"
    logging: &logconfig
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    networks:
      internal-only:
  koboldcpp:
    build:
      context: .
      dockerfile: Dockerfile.koboldcpp
    image: koboldcpp:local # local tag
    container_name: koboldcpp
    volumes:
      - "./models:/app/models/"
    logging: *logconfig
    restart: unless-stopped
    networks:
      internal-only:
    ulimits:
      memlock: -1
    # {% if 'ai-gpu' in salt['grains.get']('roles') %}
    # gpu stuff :meltyface: the command also has arguments appended to help out
    mem_limit: 50gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # {% endif %}
    command:
      [
        "python3",
        "koboldcpp.py",
        "--model",
        "/app/models/${MODEL}",
        "--port",
        "5001",
        "--threads",
        "12",
        "--stream",
        "--smartcontext",
        # {% if 'ai-gpu' in salt['grains.get']('roles') %}
        "--usemlock",
        "--usecublas",
        "0",
        "--gpulayers",
        "43" # {% endif %}
      ]
  nginx-ingress:
    image: nginx:mainline-alpine
    container_name: nginx-ingress
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    logging: *logconfig
    depends_on:
      - sillytavern
    ports:
      - "{{ nebula_ip }}:{{ ports['koboldcpp'] }}:5001"
      - "{{ nebula_ip }}:{{ ports['sillytavern'] }}:5002"
    networks:
      internal-only:
      gateway-to-external:


networks:
  internal-only:
    name: internal-only
    internal: true
  gateway-to-external:
    name: gateway-to-external
