# Based off of
# https://github.com/noneabove1182/koboldcpp-docker/blob/main/Dockerfile
# However, modified to use single stage since we're not pushing it anywhere
# and to keep openblas around.

# cuda devel image for base, best build compatibility
FROM {{ base_cuda_image }} as builder

# Update base image and install dependencies
RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y git build-essential \
    python3 pip gcc wget \
    ocl-icd-opencl-dev opencl-headers clinfo \
    libclblast-dev libopenblas-dev \
    && mkdir -p /etc/OpenCL/vendors && echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

WORKDIR /comfyui

ENV COMFYUI_VERSION=v0.2.2

RUN git clone https://github.com/comfyanonymous/ComfyUI.git --branch ${COMFYUI_VERSION} ./

RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu124

RUN pip install -r requirements.txt

CMD ["python3", "main.py", "--listen 0.0.0.0", " --port=2381"]