# comment to keep editor from exploding in rage, jinja still applies...
# {% from "maps/ports.jinja" import ports with context %}

# We use nginx as the access point; this ensures that nothing else
# is allowed general network access. 

version: "3"
services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile.comfyui
    image: comfyui:local # local tag
    container_name: comfyui
    volumes:
      - "./models:/comfyui/models/"
      - "./output:/comfyui/output/"
    logging: &logconfig
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: unless-stopped
    networks:
      comfyui-internal-only:
    ulimits:
      memlock: -1
    mem_limit: 50gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command:
      [
        "python3",
        "main.py",
        "--listen",
        "0.0.0.0",
        "--port",
        "6002"
      ]
  comfyui-nginx-ingress:
    image: nginx:mainline-alpine
    container_name: comfyui-nginx-ingress
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    logging: *logconfig
    depends_on:
      - comfyui
    ports:
      - "{{ nebula_ip }}:{{ ports['comfyui'] }}:6002"
    networks:
      comfyui-internal-only:
      comfyui-gateway-to-external:

        # TODO: limit num cpus for comfyui

networks:
  comfyui-internal-only:
    name: comfyui-internal-only
    internal: true
  comfyui-gateway-to-external:
    name: comfyui-gateway-to-external
